spring.application.name=BE
server.port=8080

# Microsoft SQL Server Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/pc_store
spring.datasource.username=postgres
spring.datasource.password=PcStore@2026

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# JWT Configuration
app.jwt.secret = ${APP_JWT_SECRET}
app.jwt.expiration-ms = 86400000

# Swagger Configuration
springdoc.api-docs.path = /v3/api-docs
springdoc.swagger-ui.path = /swagger-ui.html


# Qdrant
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=pc_components_v2
spring.ai.vectorstore.qdrant.initialize-schema=true

# GOOGLE GEMINI
# Key 1
#spring.ai.google.genai.api-key=${GEMNI_API}
# Key 2
spring.ai.google.genai.api-key=${GEMNI_API_2}

spring.ai.google.genai.chat.api-key=${spring.ai.google.genai.api-key}
spring.ai.google.genai.embedding.api-key=${spring.ai.google.genai.api-key}

spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
# MoMo Sandbox Configuration
app.momo.partner-code=${MOMO_PARTNER_CODE:MOMO}
app.momo.access-key=${MOMO_ACCESS_KEY:F8BBA842ECF85}
app.momo.secret-key=${MOMO_SECRET_KEY:K951B6PE1waDMi640xX08PD3vg6EkVlz}
app.momo.endpoint=${MOMO_ENDPOINT:https://test-payment.momo.vn/v2/gateway/api/create}
app.momo.redirect-url=${MOMO_REDIRECT_URL:http://localhost:5173/payment/result}
app.momo.ipn-url=${MOMO_IPN_URL:https://athetoid-nippily-patrice.ngrok-free.dev/api/payments/momo/ipn}
