spring.application.name=BE
server.port=8080

# Microsoft SQL Server Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/pc_store
spring.datasource.username=postgres
spring.datasource.password=PcStore@2026

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# JWT Configuration
app.jwt.secret = ${APP_JWT_SECRET}
app.jwt.expiration-ms = 86400000

# Swagger Configuration
springdoc.api-docs.path = /v3/api-docs
springdoc.swagger-ui.path = /swagger-ui.html


# Qdrant
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=pc_components_v2
spring.ai.vectorstore.qdrant.initialize-schema=true

# GOOGLE GEMINI
# Key 1
spring.ai.google.genai.api-key=AIzaSyCw98UlDj3pvgdgYPxaRJsA9e94ViLdkc4
# Key 2
#spring.ai.google.genai.api-key=AIzaSyBPiDFkc1ibSRA9TUO3VI8NVa1X5OiGjG4
spring.ai.google.genai.chat.api-key=${spring.ai.google.genai.api-key}
spring.ai.google.genai.embedding.api-key=${spring.ai.google.genai.api-key}

spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001